
# html lang
language: en

# main menu navigation
menu:
  home: /
  About: /about
  Contact: /contact
  Archives: /archives
  categories: /categories

# stylesheets loaded in the <head>
stylesheets:
- /css/therm.css

# scripts loaded in the end of the body
scripts:
- /js/therm.js
